name: Deploy Angular App to GCP

on:
  push:
    branches:
      - dev

env:
  GCP_PROJECT_ID: 'estevez-jor-agile-dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --dev

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/613099445165/locations/global/workloadIdentityPools/githubs-auth/providers/github-action'
        service_account: erp-frontend-dev@estevez-jor-agile-dev.iam.gserviceaccount.com
        #credentials_json: ${{ secrets.GCP_KEY }}

    - name: Set GCP Project
      run: gcloud config set project ${{ env.GCP_PROJECT_ID }}
      #run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
